apiVersion: v1
data:
  tunnel-credentials.json: eyJBY2NvdW50VGFnIjoiNWQ4MzhlY2IxMWRiYTRkZWJiN2Y3MTRhZWVjYzhlZjkiLCJUdW5uZWxTZWNyZXQiOiJiNVJnd2RJSjZzcjJ6Z2N2RS9ubXlVY0hPLzBDdzJaZGdtbTRRV1hUOWVNPSIsIlR1bm5lbElEIjoiZTFkMjcyZGQtN2Y1ZC00MDdkLTlmZmQtOWZkZDc1OGI4ODFlIiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  name: tunnel-credentials

